### ISSUE TITLE
Website Design

### ISSUE THREAD

**Issue by mkerwoodchamp** [Luke-Cutter/CSI-280-Project#1]
Initial Ideas:

Make a home landing page (draw a mockup of what we want the home page to look like)

Lay out how we want the site to be structured/ what pages are necessary/ essential

Lay out design ideas for the website/ what colors we want the page to mainly be

Figure out what what widgets we would need to use

List local charities we want to spotlight initially before we go higher in scope/ make dummy charities to show the concept initially

Mock-Up a homepage/ sample charity page before next class period so we can pick elements we like

**Comment by Luke-Cutter** [comment]
Initial Ideas:

Make a home landing page (draw a mockup of what we want the home page to look like)

Lay out how we want the site to be structured/ what pages are necessary/ essential

Lay out design ideas for the website/ what colors we want the page to mainly be

Figure out what what widgets we would need to use

List local charities we want to spotlight initially before we go higher in scope/ make dummy charities to show the concept initially

Mock-Up a homepage/ sample charity page before next class period so we can pick elements we like

**Comment by Luke-Cutter** [comment]
Finished the website design
