### ISSUE TITLE
Add How to Install/Run the project to README

### ISSUE THREAD

**Issue by mkerwoodchamp** [Luke-Cutter/CSI-280-Project#17]
Add a description to the README for how to install all of the project to make sure it works fine. Include things like Node.js, npm, vite, dependencies.

**Comment by alexcattani44** [comment]
Code lines to run to install:
npm install vite@latest

npm install @mui/icons-material
@mui/material @emotion/react @emotion/styled

npm install mdb-react-ui-kit

**Comment by mkerwoodchamp** [comment]
Finished with #38 pull
