### ISSUE TITLE
Framework Choice

### ISSUE THREAD

**Issue by Luke-Cutter** [Luke-Cutter/CSI-280-Project#2]
Look at frameworks, I (Luke) like React & Mantine. Come back next week Jan 30th with a choice after looking at a few (2-3) and give some advantages/ disadvantages.

https://hackr.io/blog/web-development-frameworks

**Comment by mkerwoodchamp** [comment]
Decided to use React and Vite for the website. Still a possibility for using Mantine in addition currently.
