### ISSUE TITLE
Future Issue: Choosing fonts, colors, and the CSS style of the website

### ISSUE THREAD

**Issue by Luke-Cutter** [Luke-Cutter/CSI-280-Project#26]
I will be planning and making choices with the team on how we want the page to look with colors and type. This will make it more unified throughout the website and make it easier for the team to design the website.

**Comment by mkerwoodchamp** [comment]
If you want you can use Figma.com to design what the website to look like

**Comment by Luke-Cutter** [comment]
Build a webpage in pure HTML CSS through Figma to get the design of the pages finalized

**Comment by Luke-Cutter** [comment]
Branching Issue: Write a style guide for all of this so that we have a consistent key to reference

**Comment by Luke-Cutter** [comment]
Closing this issue to be more specific about the style guidelines.
