### ISSUE TITLE
Integrate TanStack

### ISSUE THREAD

**Issue by mkerwoodchamp** [Luke-Cutter/CSI-280-Project#59]
https://tanstack.com/query/latest/docs/framework/react/overview TanStack is a framework that is used for fetching and updating data, which I feel could be useful for when we want to query our database to get the information for the website.

**Comment by alexcattani44** [comment]
I think we will be able to query the database from Django pretty easily, so we shouldn't need this. If you wanna mess around with it, go for it, but otherwise we can close this.

**Comment by alexcattani44** [comment]
Closing this, since Django will be what we use to query
