### ISSUE TITLE
Create footer

### ISSUE THREAD

**Issue by mkerwoodchamp** [Luke-Cutter/CSI-280-Project#62]
Create the footer from the Figma design as a component to be used on the majority of the pages

**Comment by mkerwoodchamp** [comment]
After looking online for a bit, I found a couple of open source footers that have what we need in terms of content but don't look exactly like what we want. Could someone take a look at these first and decide what one to use for the website or if we want to try and make our own?
[https://classic.yarnpkg.com/en/package/simple-react-footer](url)
[https://flowbite-react.com/docs/components/footer](url)

**Comment by alexcattani44** [comment]
I think this might be easier to do from scratch then reconfiguring a preexisting footer. We should be able to use basic html table tags without borders to make this? But not fully sure. Also, we can import icons from an existing library that can be colored to match our theme. I like [these](https://www.s-ings.com/typicons/) best, but there are a ton of libraries [here](https://www.npmjs.com/package/react-icons). Let me know what you think.
